### PR TITLE
Added Course schema, controller, module and service

### LINKED ISSUE #30: Course Module for backend
**Is your feature request related to a problem? Please describe.**

We need to add schemas for the server for example users, courses, doubts, contests, assignments, etc. So that they can be properly stored in the database.

**Describe the solution you'd like**

Adding models of MongoDB schemas as described in docs for nestjs.

### PR DESCRIPTION
**Pull request by ritvij14**
**Description**
I have added a course schema for mongo and also added module, service, and controller for it.

**Functioning:**
image
image

**Related Issue** 
- issue goes here

Fixes #30 

- [x] Code
- [x] New Feature
- [x] Testing

**Checklist**

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by ritvij14** [comment]
@Abhishek-kumar09 please review this.

**Comment by Devesh21700Kumar** [comment]
@Abhishek-kumar09 @ritvij14 Please add Postman tests also and the changes made in database(if connected locally)  else the controllers might give an error or conflict at a  later stage

**Comment by ritvij14** [comment]
@Abhishek-kumar09 I have added pic for running on postman as well.

**Comment by Abhishek-kumar09** [comment]
Sure, I will check that out by tomorrow @ritvij14

**Comment by Abhishek-kumar09** [comment]
Even after creating a course, the course is not fetched when I do give get request to `course/all`

**Review by Devesh21700Kumar — COMMENTED** [review]
no need for spec.ts files right now
they are just initialised unit tests.
We will need them at a later final stage

**Comment by ritvij14** [comment]
@Abhishek-kumar09 I have made the corrections.

@Devesh21700Kumar I think we can let them stay, for now, once we add a dedicated folder for tests, we can move them and then add proper unit tests for the API

**Review by Abhishek-kumar09 — APPROVED** [review]

**Comment by Abhishek-kumar09** [comment]
Thanks @ritvij14 for your patience, sorry got delayed due to some other commitments

**Pull request merged**
