### PR TITLE
Docker compose file updated and added course Schema

### PR DESCRIPTION
**Pull request by Devesh21700Kumar**
**Description**

Docker compose fil updated and added course Schema

Fixes # [ISSUE]

- [x] Code
- [x] New Featureg

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Have you docker compose locally, the db is not successfully setup, I am getting unable to connect error.
```console
edu-server-app    | [Nest] 19   - 03/25/2021, 5:53:36 PM   [InstanceLoader] AuthModule dependencies initialized +1ms
edu-server-app    | [Nest] 19   - 03/25/2021, 5:53:36 PM   [InstanceLoader] PassportModule dependencies initialized +0ms
edu-server-app    | [Nest] 19   - 03/25/2021, 5:53:36 PM   [InstanceLoader] MongooseModule dependencies initialized +0ms
edu-server-app    | [Nest] 19   - 03/25/2021, 5:53:36 PM   [InstanceLoader] ConfigModule dependencies initialized +438ms
edu-server-app    | [Nest] 19   - 03/25/2021, 5:53:36 PM   [InstanceLoader] FirebaseAdminCoreModule dependencies initialized +1ms
edu-server-app    | [Nest] 19   - 03/25/2021, 5:53:36 PM   [InstanceLoader] AppModule dependencies initialized +1ms
edu-server-app    | [Nest] 19   - 03/25/2021, 5:54:06 PM   [MongooseModule] Unable to connect to the database. Retrying (1)... +29561ms
edu-server-app    | [Nest] 19   - 03/25/2021, 5:54:39 PM   [MongooseModule] Unable to connect to the database. Retrying (2)... +33005ms
edu-server-app    | [Nest] 19   - 03/25/2021, 5:55:12 PM   [MongooseModule] Unable to connect to the database. Retrying (3)... +33004ms
edu-server-app    | [Nest] 19   - 03/25/2021, 5:55:45 PM   [MongooseModule] Unable to connect to the database. Retrying (4)... +33004ms```

**Comment by Devesh21700Kumar** [comment]
@Abhishek-kumar09  i will revert the docker-compose file for now . This error couldn't be removed  because the network and credentials for mongodb database were not given by me.
I'll revert the change in that file for now

**Comment by Devesh21700Kumar** [comment]
@Abhishek-kumar09  i've removed the mongo container for now. i'll fix the problem and make a PR for that after this.

**Comment by Abhishek-kumar09** [comment]
No we would be hosting the main mongodb on our servers which will be secured.
For now security in connection like username and password is not needed, since it will create a barrier for new developers to setup their project, as it becomes common problem after that.

**Comment by Devesh21700Kumar** [comment]
> No we would be hosting the main mongodb on our servers which will be secured.
> For now security in connection like username and password is not needed, since it will create a barrier for new developers to setup their project, as it becomes common problem after that.

Ok. then i will try to fix this issue with ur approach, I will try to do this by tomorrow in a different PR

**Comment by Devesh21700Kumar** [comment]
@Abhishek-kumar09 Thanks.. i think that this PR with schema and the readme files i had earlier committed are ok.
If u find them correct then u can merge it. Then i can pull again and make changes in docker file without merge conflicts from this PR

**Comment by Devesh21700Kumar** [comment]
> No we would be hosting the main mongodb on our servers which will be secured.
> For now security in connection like username and password is not needed, since it will create a barrier for new developers to setup their project, as it becomes common problem after that.

Yeah i've fixed that issue now.. i'll send the commit now

**Pull request closed without merging**
