### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Devesh21700Kumar**
Just added mongodb installation point to the readme

### CODE REVIEW

**Comment by Devesh21700Kumar** [comment]
@Abhishek-kumar09 @KeenWarrior the readme u said to update

**Review by Abhishek-kumar09 — CHANGES_REQUESTED** [review]
Make a subheading running with docker and mention that how they can run with docker-compose up

**Comment by Devesh21700Kumar** [comment]
> Make a subheading running with docker and mention that how they can run with docker-compose up

Sure .. Will do so

**Comment by Devesh21700Kumar** [comment]
> Make a subheading running with docker and mention that how they can run with docker-compose up

@Abhishek-kumar09 Done..

**Pull request merged**
