### PR TITLE
Fix failing tests [Hot-Fix] and some refactor and mentor population in course endpoint and other changes

### PR DESCRIPTION
**Pull request by Devesh21700Kumar**
Fix failing tests 

1).Earlier the tests were failing after findById function was renamed as getMe in service
Now testing file has been refactored accordingly and has been fixed

2).Refactored getMe in user.controller tests specfile. 

3).Also populated doubts and doubtAnswers using deep populate in get single course by Id endpoint

4). Added tests for get by email ID controller

5). Added an endpoint to add mentor to a course
and populates it in the course cards and get individual endpoints.

image

How Has This Been Tested?

Terminal commands to test code:-
1). npm run lint
2). npm run lint:fix
3). nest start
4). npm run test

### CODE REVIEW

**Review by Devesh21700Kumar — COMMENTED** [review]
Refactored getMe in user.controller tests specfile. Also populated doubts and doubtAnswers using deep populate in get single course by Id endpoint.

**Review by Abhishek-kumar09 — COMMENTED** [review]
Also add get user by ID

**Review by Devesh21700Kumar — COMMENTED** [review]
Added tests for get by email ID controller

**Review by Devesh21700Kumar — COMMENTED** [review]
@Abhishek-kumar09  Added an endpoint to add mentor to a course
and populates it in the course cards and get individual endpoints.

**Pull request merged**
